#!/usr/bin/env node
/**
 * Generate worker.js — a Cloudflare Worker that acts as a CORS proxy for
 * Domain Hunter RDAP checks. Reads src/config/tlds.json and embeds a
 * tld → rdapBase map. Only known TLDs are resolved; NO arbitrary URL
 * passthrough (anti-abuse, SPEC §13).
 */
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const TLDS_PATH = join(__dirname, '..', 'src', 'config', 'tlds.json');
const WORKER_PATH = join(__dirname, '..', 'worker.js');

function resolveRdapBase(rdapBase, tld) {
  return rdapBase.includes('{tld}') ? rdapBase.replace('{tld}', tld) : rdapBase;
}

async function main() {
  const raw = await readFile(TLDS_PATH, 'utf8');
  const registry = JSON.parse(raw);
  const infras = registry.infras;
  const tldConfigs = registry.tlds;

  const map = {};
  for (const c of tldConfigs) {
    const infra = infras[c.infra];
    const base = c.rdapBase ?? infra.rdapBase;
    map[c.tld] = resolveRdapBase(base, c.tld);
  }

  const worker = `// AUTO-GENERATED by scripts/build-worker.mjs — do not edit by hand.
// Cloudflare Worker: CORS proxy for Domain Hunter RDAP checks.
// Only resolves TLDs from the embedded map; no arbitrary URL passthrough (SPEC §13).
const TLD_MAP = ${JSON.stringify(map, null, 2)};

const UA = 'domain-hunter-worker/2.0';

// Social handle checks (server-side, bypasses browser CORS blocks).
const SOCIAL_URLS = {
  github: (n) => 'https://api.github.com/users/' + n,
  x: (n) => 'https://x.com/' + n,
  youtube: (n) => 'https://www.youtube.com/@' + n,
  instagram: (n) => 'https://www.instagram.com/' + n,
  reddit: (n) => 'https://www.reddit.com/user/' + n + '/about.json',
  tiktok: (n) =>
    'https://www.tiktok.com/oembed?url=' + encodeURIComponent('https://www.tiktok.com/@' + n),
};

function json(body, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      'content-type': 'application/json',
      'access-control-allow-origin': '*',
      'cache-control': 'no-store',
    },
  });
}

export default {
  async fetch(request) {
    const url = new URL(request.url);
    const path = url.pathname.replace(/^\\/+/, '');

    if (!path) {
      return json({ usage: 'GET /{domain} | GET /social/{platform}/{name}' });
    }

    const socialMatch = path.match(/^social\\/([a-z]+)\\/([a-z0-9_.]{1,30})$/);
    if (socialMatch) {
      const platform = socialMatch[1];
      const name = socialMatch[2];
      const buildUrl = SOCIAL_URLS[platform];
      if (!buildUrl) return json({ platform, error: 'unknown platform' }, 400);
      try {
        const res = await fetch(buildUrl(name), {
          headers: { 'user-agent': UA },
          redirect: 'follow',
        });
        const status = res.status === 200 ? 'taken' : res.status === 404 ? 'free' : 'unknown';
        return json({ platform, name, status });
      } catch (err) {
        return json({ platform, name, status: 'unknown', error: err?.message ?? 'fetch failed' });
      }
    }

    let domain;
    try {
      domain = decodeURIComponent(path);
    } catch {
      return json({ error: 'invalid encoding' }, 400);
    }

    const labels = domain.split('.');
    if (labels.length < 2) {
      return json({ domain, error: 'invalid domain' }, 400);
    }

    const tld = labels[labels.length - 1].toLowerCase();
    const base = TLD_MAP[tld];
    if (!base) {
      return json({ domain, tld, error: 'unknown tld' }, 400);
    }

    const upstream = base + domain;
    try {
      const res = await fetch(upstream, {
        headers: { 'user-agent': UA },
        redirect: 'manual',
      });
      return json({ domain, tld, status: res.status, free: res.status === 404 });
    } catch (err) {
      return json({ domain, tld, status: 0, free: false, error: err?.message ?? 'fetch failed' });
    }
  },
};
`;

  await writeFile(WORKER_PATH, worker, 'utf8');
  console.log(`worker.js generated with ${Object.keys(map).length} TLDs -> ${WORKER_PATH}`);
}

main().catch((err) => {
  console.error('build-worker failed:', err);
  process.exit(1);
});
